// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/common/audit_record.proto

package commonv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditReplacement is the audit-safe projection of a masking replacement. The
// original value is present only when the operator opts in via
// GUARDRAILS_AUDIT_STORE_ORIGINAL_TEXTS (off by default); see original.
type AuditReplacement struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RuleId      string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	DataType    DataType               `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"data_type,omitempty"`
	Placeholder string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	// original is the raw pre-masking value behind placeholder. Empty unless
	// GUARDRAILS_AUDIT_STORE_ORIGINAL_TEXTS is enabled; decrypted by the API
	// before it is returned. SECURITY: raw sensitive data — access-control it.
	Original      string `protobuf:"bytes,4,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReplacement) Reset() {
	*x = AuditReplacement{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReplacement) ProtoMessage() {}

func (x *AuditReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReplacement.ProtoReflect.Descriptor instead.
func (*AuditReplacement) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescGZIP(), []int{0}
}

func (x *AuditReplacement) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AuditReplacement) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *AuditReplacement) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *AuditReplacement) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

// AuditRecord is one per-request masking audit entry.
type AuditRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Mode               string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Path               string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	TriggeredRuleIds   []string               `protobuf:"bytes,6,rep,name=triggered_rule_ids,json=triggeredRuleIds,proto3" json:"triggered_rule_ids,omitempty"`
	TriggeredDataTypes []DataType             `protobuf:"varint,7,rep,packed,name=triggered_data_types,json=triggeredDataTypes,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"triggered_data_types,omitempty"`
	Replacements       []*AuditReplacement    `protobuf:"bytes,8,rep,name=replacements,proto3" json:"replacements,omitempty"`
	MaskedTexts        []string               `protobuf:"bytes,9,rep,name=masked_texts,json=maskedTexts,proto3" json:"masked_texts,omitempty"`
	// masked_response_texts holds the post-masking model response texts
	// (placeholders substituted, originals absent) — the response counterpart of
	// masked_texts. Populated only when GUARDRAILS_AUDIT_STORE_MASKED_RESPONSE_TEXTS
	// is enabled.
	MaskedResponseTexts []string `protobuf:"bytes,10,rep,name=masked_response_texts,json=maskedResponseTexts,proto3" json:"masked_response_texts,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescGZIP(), []int{1}
}

func (x *AuditRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditRecord) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AuditRecord) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AuditRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuditRecord) GetTriggeredRuleIds() []string {
	if x != nil {
		return x.TriggeredRuleIds
	}
	return nil
}

func (x *AuditRecord) GetTriggeredDataTypes() []DataType {
	if x != nil {
		return x.TriggeredDataTypes
	}
	return nil
}

func (x *AuditRecord) GetReplacements() []*AuditReplacement {
	if x != nil {
		return x.Replacements
	}
	return nil
}

func (x *AuditRecord) GetMaskedTexts() []string {
	if x != nil {
		return x.MaskedTexts
	}
	return nil
}

func (x *AuditRecord) GetMaskedResponseTexts() []string {
	if x != nil {
		return x.MaskedResponseTexts
	}
	return nil
}

var File_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDesc = "" +
	"\n" +
	"Aapi/proto/cloudru/guardrails/v1/service/common/audit_record.proto\x12$cloudru.guardrails.v1.service.common\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a>api/proto/cloudru/guardrails/v1/service/common/data_type.proto\"\xb6\x01\n" +
	"\x10AuditReplacement\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12K\n" +
	"\tdata_type\x18\x02 \x01(\x0e2..cloudru.guardrails.v1.service.common.DataTypeR\bdataType\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\boriginal\x18\x04 \x01(\tR\boriginal\"\xfa\x04\n" +
	"\vAuditRecord\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12,\n" +
	"\x12triggered_rule_ids\x18\x06 \x03(\tR\x10triggeredRuleIds\x12`\n" +
	"\x14triggered_data_types\x18\a \x03(\x0e2..cloudru.guardrails.v1.service.common.DataTypeR\x12triggeredDataTypes\x12Z\n" +
	"\freplacements\x18\b \x03(\v26.cloudru.guardrails.v1.service.common.AuditReplacementR\freplacements\x12!\n" +
	"\fmasked_texts\x18\t \x03(\tR\vmaskedTexts\x122\n" +
	"\x15masked_response_texts\x18\n" +
	" \x03(\tR\x13maskedResponseTexts:\x90\x01\x92A\x8c\x01\n" +
	"\x89\x01*\fAudit Record2yOne per-request masking audit entry. Original values are omitted unless GUARDRAILS_AUDIT_STORE_ORIGINAL_TEXTS is enabled.BtZrgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common;commonv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_goTypes = []any{
	(*AuditReplacement)(nil),      // 0: cloudru.guardrails.v1.service.common.AuditReplacement
	(*AuditRecord)(nil),           // 1: cloudru.guardrails.v1.service.common.AuditRecord
	(DataType)(0),                 // 2: cloudru.guardrails.v1.service.common.DataType
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_depIdxs = []int32{
	2, // 0: cloudru.guardrails.v1.service.common.AuditReplacement.data_type:type_name -> cloudru.guardrails.v1.service.common.DataType
	3, // 1: cloudru.guardrails.v1.service.common.AuditRecord.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: cloudru.guardrails.v1.service.common.AuditRecord.triggered_data_types:type_name -> cloudru.guardrails.v1.service.common.DataType
	0, // 3: cloudru.guardrails.v1.service.common.AuditRecord.replacements:type_name -> cloudru.guardrails.v1.service.common.AuditReplacement
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto != nil {
		return
	}
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_common_audit_record_proto_depIdxs = nil
}
