// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/common/data_type.proto

package commonv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataType is a user-facing toggle category of detection rules. It mirrors
// internal/models.DataType (numeric IDs must stay consistent across the enum,
// the YAML rule files and the API). CUSTOM is reserved for rules created via
// the configuration API that do not fit a built-in category.
type DataType int32

const (
	// Unspecified data type.
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	// Credentials and account identifiers.
	DataType_DATA_TYPE_CREDENTIALS DataType = 1
	// API keys and tokens for service access.
	DataType_DATA_TYPE_API_KEYS DataType = 2
	// Access tokens and bearer tokens.
	DataType_DATA_TYPE_ACCESS_TOKENS DataType = 3
	// IP addresses.
	DataType_DATA_TYPE_IP_ADDRESSES DataType = 4
	// Personal identifiable information.
	DataType_DATA_TYPE_PERSONAL_DATA DataType = 5
	// Custom category: rules created via the configuration API.
	DataType_DATA_TYPE_CUSTOM DataType = 6
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_CREDENTIALS",
		2: "DATA_TYPE_API_KEYS",
		3: "DATA_TYPE_ACCESS_TOKENS",
		4: "DATA_TYPE_IP_ADDRESSES",
		5: "DATA_TYPE_PERSONAL_DATA",
		6: "DATA_TYPE_CUSTOM",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED":   0,
		"DATA_TYPE_CREDENTIALS":   1,
		"DATA_TYPE_API_KEYS":      2,
		"DATA_TYPE_ACCESS_TOKENS": 3,
		"DATA_TYPE_IP_ADDRESSES":  4,
		"DATA_TYPE_PERSONAL_DATA": 5,
		"DATA_TYPE_CUSTOM":        6,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescGZIP(), []int{0}
}

var File_api_proto_cloudru_guardrails_v1_service_common_data_type_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDesc = "" +
	"\n" +
	">api/proto/cloudru/guardrails/v1/service/common/data_type.proto\x12$cloudru.guardrails.v1.service.common\x1a.protoc-gen-openapiv2/options/annotations.proto*\xa7\x02\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DATA_TYPE_CREDENTIALS\x10\x01\x12\x16\n" +
	"\x12DATA_TYPE_API_KEYS\x10\x02\x12\x1b\n" +
	"\x17DATA_TYPE_ACCESS_TOKENS\x10\x03\x12\x1a\n" +
	"\x16DATA_TYPE_IP_ADDRESSES\x10\x04\x12\x1b\n" +
	"\x17DATA_TYPE_PERSONAL_DATA\x10\x05\x12\x14\n" +
	"\x10DATA_TYPE_CUSTOM\x10\x06\x1aa\x92A^\n" +
	"CSensitive data category. Exclude DATA_TYPE_UNSPECIFIED in requests.:\x17\"DATA_TYPE_CREDENTIALS\"BtZrgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common;commonv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_goTypes = []any{
	(DataType)(0), // 0: cloudru.guardrails.v1.service.common.DataType
}
var file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_common_data_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_depIdxs,
		EnumInfos:         file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_enumTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_common_data_type_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_depIdxs = nil
}
