// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/common/guardrail_rule.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Masking describes how a detected value is replaced during masking.
type Masking struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CaptureGroups selects which regex capture groups to mask; empty masks the
	// full match.
	CaptureGroups []int32 `protobuf:"varint,1,rep,packed,name=capture_groups,json=captureGroups,proto3" json:"capture_groups,omitempty"`
	// Placeholder is the placeholder base name; the engine renders <NAME_N>.
	Placeholder   string `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Masking) Reset() {
	*x = Masking{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Masking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Masking) ProtoMessage() {}

func (x *Masking) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Masking.ProtoReflect.Descriptor instead.
func (*Masking) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescGZIP(), []int{0}
}

func (x *Masking) GetCaptureGroups() []int32 {
	if x != nil {
		return x.CaptureGroups
	}
	return nil
}

func (x *Masking) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// GuardrailRule is a single detection rule (built-in or custom). It mirrors the
// engine rule (pkg/guardrails/regex/rule.Rule). It is used as both the request
// body (create/update) and the response for rule read/write RPCs; source and
// enabled are response-only and ignored on input.
type GuardrailRule struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RuleId     string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group      string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	DataType   DataType               `protobuf:"varint,4,opt,name=data_type,json=dataType,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"data_type,omitempty"`
	Regex      string                 `protobuf:"bytes,5,opt,name=regex,proto3" json:"regex,omitempty"`
	Keywords   []string               `protobuf:"bytes,6,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Validators []string               `protobuf:"bytes,7,rep,name=validators,proto3" json:"validators,omitempty"`
	MinLength  int32                  `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	Entropy    float64                `protobuf:"fixed64,9,opt,name=entropy,proto3" json:"entropy,omitempty"`
	Banlist    []string               `protobuf:"bytes,10,rep,name=banlist,proto3" json:"banlist,omitempty"`
	Masking    *Masking               `protobuf:"bytes,11,opt,name=masking,proto3" json:"masking,omitempty"`
	// Response-only fields.
	Source        string `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	Enabled       *bool  `protobuf:"varint,13,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardrailRule) Reset() {
	*x = GuardrailRule{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardrailRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardrailRule) ProtoMessage() {}

func (x *GuardrailRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardrailRule.ProtoReflect.Descriptor instead.
func (*GuardrailRule) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescGZIP(), []int{1}
}

func (x *GuardrailRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GuardrailRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuardrailRule) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GuardrailRule) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *GuardrailRule) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

func (x *GuardrailRule) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *GuardrailRule) GetValidators() []string {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *GuardrailRule) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *GuardrailRule) GetEntropy() float64 {
	if x != nil {
		return x.Entropy
	}
	return 0
}

func (x *GuardrailRule) GetBanlist() []string {
	if x != nil {
		return x.Banlist
	}
	return nil
}

func (x *GuardrailRule) GetMasking() *Masking {
	if x != nil {
		return x.Masking
	}
	return nil
}

func (x *GuardrailRule) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GuardrailRule) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

var File_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDesc = "" +
	"\n" +
	"Capi/proto/cloudru/guardrails/v1/service/common/guardrail_rule.proto\x12$cloudru.guardrails.v1.service.common\x1a/proto/protovalidate/buf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a>api/proto/cloudru/guardrails/v1/service/common/data_type.proto\"\xcc\x01\n" +
	"\aMasking\x12d\n" +
	"\x0ecapture_groups\x18\x01 \x03(\x05B=\x92A:28Regex capture groups to mask; empty masks the full matchR\rcaptureGroups\x12[\n" +
	"\vplaceholder\x18\x02 \x01(\tB9\x92A62+Placeholder base name; rendered as <NAME_N>J\a\"EMAIL\"R\vplaceholder\"\xfb\b\n" +
	"\rGuardrailRule\x12Q\n" +
	"\arule_id\x18\x01 \x01(\tB8\x92A+2\x16Unique rule identifierJ\x11\"my-custom-email\"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x06ruleId\x12;\n" +
	"\x04name\x18\x02 \x01(\tB'\x92A\x1a2\x18Human-readable rule name\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x125\n" +
	"\x05group\x18\x03 \x01(\tB\x1f\x92A\x1c2\x1aRule group (informational)R\x05group\x12q\n" +
	"\tdata_type\x18\x04 \x01(\x0e2..cloudru.guardrails.v1.service.common.DataTypeB$\x92A!2\x1fData category this rule detectsR\bdataType\x127\n" +
	"\x05regex\x18\x05 \x01(\tB!\x92A\x172\x15RE2 detection pattern\xbaH\x04r\x02\x10\x01R\x05regex\x12B\n" +
	"\bkeywords\x18\x06 \x03(\tB&\x92A#2!Optional keyword pre-filter termsR\bkeywords\x12^\n" +
	"\n" +
	"validators\x18\a \x03(\tB>\x92A;29Optional candidate validators (e.g. luhn, entropy, ip_v4)R\n" +
	"validators\x12N\n" +
	"\n" +
	"min_length\x18\b \x01(\x05B/\x92A,2*Minimum matched length before a hit countsR\tminLength\x12P\n" +
	"\aentropy\x18\t \x01(\x01B6\x92A321Minimum Shannon entropy for the entropy validatorR\aentropy\x12<\n" +
	"\abanlist\x18\n" +
	" \x03(\tB\"\x92A\x1f2\x1dValues excluded from matchingR\abanlist\x12j\n" +
	"\amasking\x18\v \x01(\v2-.cloudru.guardrails.v1.service.common.MaskingB!\x92A\x1e2\x1cMasking policy for this ruleR\amasking\x12A\n" +
	"\x06source\x18\f \x01(\tB)\x92A&2$Response-only: \"builtin\" or \"custom\"R\x06source\x12X\n" +
	"\aenabled\x18\r \x01(\bB9\x92A624Response-only: whether the rule is currently enabledH\x00R\aenabled\x88\x01\x01:^\x92A[\n" +
	"Y*\x0eGuardrail Rule2GA detection rule: RE2 regex plus optional validators and masking policyB\n" +
	"\n" +
	"\b_enabledBtZrgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common;commonv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_goTypes = []any{
	(*Masking)(nil),       // 0: cloudru.guardrails.v1.service.common.Masking
	(*GuardrailRule)(nil), // 1: cloudru.guardrails.v1.service.common.GuardrailRule
	(DataType)(0),         // 2: cloudru.guardrails.v1.service.common.DataType
}
var file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_depIdxs = []int32{
	2, // 0: cloudru.guardrails.v1.service.common.GuardrailRule.data_type:type_name -> cloudru.guardrails.v1.service.common.DataType
	0, // 1: cloudru.guardrails.v1.service.common.GuardrailRule.masking:type_name -> cloudru.guardrails.v1.service.common.Masking
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto != nil {
		return
	}
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_init()
	file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_common_guardrail_rule_proto_depIdxs = nil
}
