// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/common/placeholder.proto

package commonv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Placeholder is one original->placeholder substitution from a dry-run scan.
// It carries the original value, which is safe here because a scan operates on
// the caller's own sample and persists nothing.
type Placeholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Original      string                 `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	RuleId        string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placeholder) Reset() {
	*x = Placeholder{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholder) ProtoMessage() {}

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescGZIP(), []int{0}
}

func (x *Placeholder) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *Placeholder) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *Placeholder) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

var File_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDesc = "" +
	"\n" +
	"@api/proto/cloudru/guardrails/v1/service/common/placeholder.proto\x12$cloudru.guardrails.v1.service.common\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x81\x02\n" +
	"\vPlaceholder\x12Z\n" +
	"\vplaceholder\x18\x01 \x01(\tB8\x92A523Placeholder that replaced the value, e.g. <EMAIL_1>R\vplaceholder\x12Z\n" +
	"\boriginal\x18\x02 \x01(\tB>\x92A;29Original detected value (caller's own sample; not stored)R\boriginal\x12:\n" +
	"\arule_id\x18\x03 \x01(\tB!\x92A\x1e2\x1cRule that produced the matchR\x06ruleIdBtZrgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common;commonv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_goTypes = []any{
	(*Placeholder)(nil), // 0: cloudru.guardrails.v1.service.common.Placeholder
}
var file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_common_placeholder_proto_depIdxs = nil
}
