// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/common/settings.proto

package commonv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GuardrailsSettings is the global (instance-wide) guardrails configuration.
// It is used as both the update request body and the read/update response.
type GuardrailsSettings struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Enabled   bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DataTypes []DataType             `protobuf:"varint,2,rep,packed,name=data_types,json=dataTypes,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"data_types,omitempty"`
	// mode is "enforce" (default) or "detect"; empty resolves to enforce.
	Mode          string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardrailsSettings) Reset() {
	*x = GuardrailsSettings{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardrailsSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardrailsSettings) ProtoMessage() {}

func (x *GuardrailsSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardrailsSettings.ProtoReflect.Descriptor instead.
func (*GuardrailsSettings) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescGZIP(), []int{0}
}

func (x *GuardrailsSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GuardrailsSettings) GetDataTypes() []DataType {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *GuardrailsSettings) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

var File_api_proto_cloudru_guardrails_v1_service_common_settings_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDesc = "" +
	"\n" +
	"=api/proto/cloudru/guardrails/v1/service/common/settings.proto\x12$cloudru.guardrails.v1.service.common\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a>api/proto/cloudru/guardrails/v1/service/common/data_type.proto\"\xe6\x02\n" +
	"\x12GuardrailsSettings\x12B\n" +
	"\aenabled\x18\x01 \x01(\bB(\x92A%2#Whether masking is enabled globallyR\aenabled\x12k\n" +
	"\n" +
	"data_types\x18\x02 \x03(\x0e2..cloudru.guardrails.v1.service.common.DataTypeB\x1c\x92A\x192\x17Enabled data categoriesR\tdataTypes\x12U\n" +
	"\x04mode\x18\x03 \x01(\tBA\x92A>21Enforcement mode: \"enforce\" (default) or \"detect\"J\t\"enforce\"R\x04mode:H\x92AE\n" +
	"C*\x13Guardrails Settings2,Global masking policy applied to all trafficBtZrgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common;commonv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_goTypes = []any{
	(*GuardrailsSettings)(nil), // 0: cloudru.guardrails.v1.service.common.GuardrailsSettings
	(DataType)(0),              // 1: cloudru.guardrails.v1.service.common.DataType
}
var file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_depIdxs = []int32{
	1, // 0: cloudru.guardrails.v1.service.common.GuardrailsSettings.data_types:type_name -> cloudru.guardrails.v1.service.common.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_common_settings_proto != nil {
		return
	}
	file_api_proto_cloudru_guardrails_v1_service_common_data_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_common_settings_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_common_settings_proto_depIdxs = nil
}
