// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_test.go -package=get_test
//

// Package get_test is a generated GoMock package.
package get_test

import (
	context "context"
	reflect "reflect"

	get "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/internal/usecases/rules/get"
	rule "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/guardrails/regex/rule"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandHandler is a mock of CommandHandler interface.
type MockCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommandHandlerMockRecorder
	isgomock struct{}
}

// MockCommandHandlerMockRecorder is the mock recorder for MockCommandHandler.
type MockCommandHandlerMockRecorder struct {
	mock *MockCommandHandler
}

// NewMockCommandHandler creates a new mock instance.
func NewMockCommandHandler(ctrl *gomock.Controller) *MockCommandHandler {
	mock := &MockCommandHandler{ctrl: ctrl}
	mock.recorder = &MockCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandHandler) EXPECT() *MockCommandHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockCommandHandler) Handle(ctx context.Context, cmd get.Command) (get.CommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, cmd)
	ret0, _ := ret[0].(get.CommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCommandHandlerMockRecorder) Handle(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCommandHandler)(nil).Handle), ctx, cmd)
}

// MockRuleStore is a mock of RuleStore interface.
type MockRuleStore struct {
	ctrl     *gomock.Controller
	recorder *MockRuleStoreMockRecorder
	isgomock struct{}
}

// MockRuleStoreMockRecorder is the mock recorder for MockRuleStore.
type MockRuleStoreMockRecorder struct {
	mock *MockRuleStore
}

// NewMockRuleStore creates a new mock instance.
func NewMockRuleStore(ctrl *gomock.Controller) *MockRuleStore {
	mock := &MockRuleStore{ctrl: ctrl}
	mock.recorder = &MockRuleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleStore) EXPECT() *MockRuleStoreMockRecorder {
	return m.recorder
}

// GetRule mocks base method.
func (m *MockRuleStore) GetRule(ctx context.Context, id string) (rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockRuleStoreMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockRuleStore)(nil).GetRule), ctx, id)
}

// ListDisabledRuleIDs mocks base method.
func (m *MockRuleStore) ListDisabledRuleIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDisabledRuleIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDisabledRuleIDs indicates an expected call of ListDisabledRuleIDs.
func (mr *MockRuleStoreMockRecorder) ListDisabledRuleIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDisabledRuleIDs", reflect.TypeOf((*MockRuleStore)(nil).ListDisabledRuleIDs), ctx)
}

// MockBuiltins is a mock of Builtins interface.
type MockBuiltins struct {
	ctrl     *gomock.Controller
	recorder *MockBuiltinsMockRecorder
	isgomock struct{}
}

// MockBuiltinsMockRecorder is the mock recorder for MockBuiltins.
type MockBuiltinsMockRecorder struct {
	mock *MockBuiltins
}

// NewMockBuiltins creates a new mock instance.
func NewMockBuiltins(ctrl *gomock.Controller) *MockBuiltins {
	mock := &MockBuiltins{ctrl: ctrl}
	mock.recorder = &MockBuiltinsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuiltins) EXPECT() *MockBuiltinsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBuiltins) Get(id string) (rule.Rule, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(rule.Rule)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBuiltinsMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBuiltins)(nil).Get), id)
}
