// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package models

import (
	"errors"
	"fmt"
)

const (
	// DataTypeUNSPECIFIED is a DataType of type UNSPECIFIED.
	DataTypeUNSPECIFIED DataType = iota
	// DataTypeCREDENTIALS is a DataType of type CREDENTIALS.
	DataTypeCREDENTIALS
	// DataTypeAPIKEYS is a DataType of type API_KEYS.
	DataTypeAPIKEYS
	// DataTypeACCESSTOKENS is a DataType of type ACCESS_TOKENS.
	DataTypeACCESSTOKENS
	// DataTypeIPADDRESSES is a DataType of type IP_ADDRESSES.
	DataTypeIPADDRESSES
	// DataTypePERSONALDATA is a DataType of type PERSONAL_DATA.
	DataTypePERSONALDATA
	// DataTypeCUSTOM is a DataType of type CUSTOM.
	DataTypeCUSTOM
)

var ErrInvalidDataType = errors.New("not a valid DataType")

const _DataTypeName = "UNSPECIFIEDCREDENTIALSAPI_KEYSACCESS_TOKENSIP_ADDRESSESPERSONAL_DATACUSTOM"

var _DataTypeMap = map[DataType]string{
	DataTypeUNSPECIFIED:  _DataTypeName[0:11],
	DataTypeCREDENTIALS:  _DataTypeName[11:22],
	DataTypeAPIKEYS:      _DataTypeName[22:30],
	DataTypeACCESSTOKENS: _DataTypeName[30:43],
	DataTypeIPADDRESSES:  _DataTypeName[43:55],
	DataTypePERSONALDATA: _DataTypeName[55:68],
	DataTypeCUSTOM:       _DataTypeName[68:74],
}

// String implements the Stringer interface.
func (x DataType) String() string {
	if str, ok := _DataTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("DataType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DataType) IsValid() bool {
	_, ok := _DataTypeMap[x]
	return ok
}

var _DataTypeValue = map[string]DataType{
	_DataTypeName[0:11]:  DataTypeUNSPECIFIED,
	_DataTypeName[11:22]: DataTypeCREDENTIALS,
	_DataTypeName[22:30]: DataTypeAPIKEYS,
	_DataTypeName[30:43]: DataTypeACCESSTOKENS,
	_DataTypeName[43:55]: DataTypeIPADDRESSES,
	_DataTypeName[55:68]: DataTypePERSONALDATA,
	_DataTypeName[68:74]: DataTypeCUSTOM,
}

// ParseDataType attempts to convert a string to a DataType.
func ParseDataType(name string) (DataType, error) {
	if x, ok := _DataTypeValue[name]; ok {
		return x, nil
	}
	return DataType(0), fmt.Errorf("%s is %w", name, ErrInvalidDataType)
}
