// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_test.go -package=mask_test
//

// Package mask_test is a generated GoMock package.
package mask_test

import (
	reflect "reflect"

	registry "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/guardrails/regex/registry"
	sensitive "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/guardrails/regex/scanners/sensitive"
	gomock "go.uber.org/mock/gomock"
)

// MockSensitiveScanner is a mock of SensitiveScanner interface.
type MockSensitiveScanner struct {
	ctrl     *gomock.Controller
	recorder *MockSensitiveScannerMockRecorder
	isgomock struct{}
}

// MockSensitiveScannerMockRecorder is the mock recorder for MockSensitiveScanner.
type MockSensitiveScannerMockRecorder struct {
	mock *MockSensitiveScanner
}

// NewMockSensitiveScanner creates a new mock instance.
func NewMockSensitiveScanner(ctrl *gomock.Controller) *MockSensitiveScanner {
	mock := &MockSensitiveScanner{ctrl: ctrl}
	mock.recorder = &MockSensitiveScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSensitiveScanner) EXPECT() *MockSensitiveScannerMockRecorder {
	return m.recorder
}

// ScanRules mocks base method.
func (m *MockSensitiveScanner) ScanRules(text string, rules []registry.CompiledRule) ([]sensitive.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanRules", text, rules)
	ret0, _ := ret[0].([]sensitive.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanRules indicates an expected call of ScanRules.
func (mr *MockSensitiveScannerMockRecorder) ScanRules(text, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanRules", reflect.TypeOf((*MockSensitiveScanner)(nil).ScanRules), text, rules)
}

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// ResolveForDataTypes mocks base method.
func (m *MockRegistry) ResolveForDataTypes(dataTypes []uint32) ([]string, []registry.CompiledRule) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveForDataTypes", dataTypes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]registry.CompiledRule)
	return ret0, ret1
}

// ResolveForDataTypes indicates an expected call of ResolveForDataTypes.
func (mr *MockRegistryMockRecorder) ResolveForDataTypes(dataTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveForDataTypes", reflect.TypeOf((*MockRegistry)(nil).ResolveForDataTypes), dataTypes)
}
