package extproc

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
)

// deriveStateKey computes the masking-state store key from the request's
// x-request-id. The key is HMAC-SHA256(salt, requestID) so a client-supplied
// or predictable x-request-id cannot be used to guess or collide with another
// request's stored state (which holds original sensitive values).
//
// TRUST ASSUMPTION: x-request-id MUST be generated by a trusted edge proxy and
// MUST NOT be settable or predictable by the client. The salt does not defend
// against a client that controls x-request-id — the service computes
// HMAC(salt, id) on the client's behalf — so the edge proxy must own the id
// (Envoy: generate_request_id: true, preserve_external_request_id: false; see
// examples/quickstart/proxy-config.yaml and docs/operations.md). Without that,
// a shared store backend (redis/postgres) allows cross-request disclosure or
// clobbering of stored originals.
//
// The derivation is deterministic, so both the request and response phases —
// and, with a shared salt, different replicas — resolve the same key. An empty
// salt falls back to an unkeyed SHA-256, which still never uses the raw
// external value as the store key; the app logs a startup warning in that case.
//
// An empty requestID yields an empty key (the caller then skips the store).
func deriveStateKey(salt, requestID string) string {
	if requestID == "" {
		return ""
	}
	if salt == "" {
		sum := sha256.Sum256([]byte(requestID))
		return hex.EncodeToString(sum[:])
	}
	mac := hmac.New(sha256.New, []byte(salt))
	mac.Write([]byte(requestID))
	return hex.EncodeToString(mac.Sum(nil))
}
