// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/bulk_set_rules_enabled.proto

package contractsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BulkSetRulesEnabledRequest enables or disables many rules in one call.
type BulkSetRulesEnabledRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ids   []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// enabled is required and applies to every id.
	Enabled       *bool `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSetRulesEnabledRequest) Reset() {
	*x = BulkSetRulesEnabledRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSetRulesEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSetRulesEnabledRequest) ProtoMessage() {}

func (x *BulkSetRulesEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSetRulesEnabledRequest.ProtoReflect.Descriptor instead.
func (*BulkSetRulesEnabledRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescGZIP(), []int{0}
}

func (x *BulkSetRulesEnabledRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BulkSetRulesEnabledRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// BulkSetRuleResult is one rule's outcome in a bulk operation.
type BulkSetRuleResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RuleId string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// status is "ok" or "error".
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// error is set when status is "error".
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSetRuleResult) Reset() {
	*x = BulkSetRuleResult{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSetRuleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSetRuleResult) ProtoMessage() {}

func (x *BulkSetRuleResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSetRuleResult.ProtoReflect.Descriptor instead.
func (*BulkSetRuleResult) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescGZIP(), []int{1}
}

func (x *BulkSetRuleResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *BulkSetRuleResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BulkSetRuleResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BulkSetRulesEnabledResponse reports the per-rule outcome. The operation is
// best-effort: each id is attempted independently and failures are reported
// per item rather than aborting the batch.
type BulkSetRulesEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BulkSetRuleResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSetRulesEnabledResponse) Reset() {
	*x = BulkSetRulesEnabledResponse{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSetRulesEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSetRulesEnabledResponse) ProtoMessage() {}

func (x *BulkSetRulesEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSetRulesEnabledResponse.ProtoReflect.Descriptor instead.
func (*BulkSetRulesEnabledResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescGZIP(), []int{2}
}

func (x *BulkSetRulesEnabledResponse) GetResults() []*BulkSetRuleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDesc = "" +
	"\n" +
	"Napi/proto/cloudru/guardrails/v1/service/contracts/bulk_set_rules_enabled.proto\x12'cloudru.guardrails.v1.service.contracts\x1a/proto/protovalidate/buf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xbb\x01\n" +
	"\x1aBulkSetRulesEnabledRequest\x12<\n" +
	"\x03ids\x18\x01 \x03(\tB*\x92A\x1c2\x1aRule identifiers to update\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x03ids\x12S\n" +
	"\aenabled\x18\x02 \x01(\bB4\x92A+2)Desired enabled state applied to every id\xbaH\x03\xc8\x01\x01H\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"Z\n" +
	"\x11BulkSetRuleResult\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"s\n" +
	"\x1bBulkSetRulesEnabledResponse\x12T\n" +
	"\aresults\x18\x01 \x03(\v2:.cloudru.guardrails.v1.service.contracts.BulkSetRuleResultR\aresultsBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_goTypes = []any{
	(*BulkSetRulesEnabledRequest)(nil),  // 0: cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledRequest
	(*BulkSetRuleResult)(nil),           // 1: cloudru.guardrails.v1.service.contracts.BulkSetRuleResult
	(*BulkSetRulesEnabledResponse)(nil), // 2: cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledResponse
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_depIdxs = []int32{
	1, // 0: cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledResponse.results:type_name -> cloudru.guardrails.v1.service.contracts.BulkSetRuleResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_init()
}
func file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto != nil {
		return
	}
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_bulk_set_rules_enabled_proto_depIdxs = nil
}
