// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/get_rule.proto

package contractsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRuleRequest reads one rule by ID.
type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescGZIP(), []int{0}
}

func (x *GetRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDesc = "" +
	"\n" +
	"@api/proto/cloudru/guardrails/v1/service/contracts/get_rule.proto\x12'cloudru.guardrails.v1.service.contracts\x1a/proto/protovalidate/buf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"F\n" +
	"\x0eGetRuleRequest\x124\n" +
	"\arule_id\x18\x01 \x01(\tB\x1b\x92A\x112\x0fRule identifier\xbaH\x04r\x02\x10\x01R\x06ruleIdBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_goTypes = []any{
	(*GetRuleRequest)(nil), // 0: cloudru.guardrails.v1.service.contracts.GetRuleRequest
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_rule_proto_depIdxs = nil
}
