// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/get_data_types.proto

package contractsv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDataTypesRequest lists the toggleable data-type groups.
type GetDataTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataTypesRequest) Reset() {
	*x = GetDataTypesRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataTypesRequest) ProtoMessage() {}

func (x *GetDataTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataTypesRequest.ProtoReflect.Descriptor instead.
func (*GetDataTypesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescGZIP(), []int{0}
}

// DataTypeInfo describes one toggleable data-type group.
type DataTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      int32                  `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTypeInfo) Reset() {
	*x = DataTypeInfo{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypeInfo) ProtoMessage() {}

func (x *DataTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypeInfo.ProtoReflect.Descriptor instead.
func (*DataTypeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescGZIP(), []int{1}
}

func (x *DataTypeInfo) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *DataTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataTypeInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DataTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetDataTypesResponse is the catalog of data-type groups plus CUSTOM.
type GetDataTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataTypes     []*DataTypeInfo        `protobuf:"bytes,1,rep,name=data_types,json=dataTypes,proto3" json:"data_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataTypesResponse) Reset() {
	*x = GetDataTypesResponse{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataTypesResponse) ProtoMessage() {}

func (x *GetDataTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataTypesResponse.ProtoReflect.Descriptor instead.
func (*GetDataTypesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescGZIP(), []int{2}
}

func (x *GetDataTypesResponse) GetDataTypes() []*DataTypeInfo {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDesc = "" +
	"\n" +
	"Fapi/proto/cloudru/guardrails/v1/service/contracts/get_data_types.proto\x12'cloudru.guardrails.v1.service.contracts\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x15\n" +
	"\x13GetDataTypesRequest\"\x9f\x01\n" +
	"\fDataTypeInfo\x126\n" +
	"\tdata_type\x18\x01 \x01(\x05B\x19\x92A\x162\x14Numeric data-type IDR\bdataType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"l\n" +
	"\x14GetDataTypesResponse\x12T\n" +
	"\n" +
	"data_types\x18\x01 \x03(\v25.cloudru.guardrails.v1.service.contracts.DataTypeInfoR\tdataTypesBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_goTypes = []any{
	(*GetDataTypesRequest)(nil),  // 0: cloudru.guardrails.v1.service.contracts.GetDataTypesRequest
	(*DataTypeInfo)(nil),         // 1: cloudru.guardrails.v1.service.contracts.DataTypeInfo
	(*GetDataTypesResponse)(nil), // 2: cloudru.guardrails.v1.service.contracts.GetDataTypesResponse
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_depIdxs = []int32{
	1, // 0: cloudru.guardrails.v1.service.contracts.GetDataTypesResponse.data_types:type_name -> cloudru.guardrails.v1.service.contracts.DataTypeInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_data_types_proto_depIdxs = nil
}
