// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/get_version.proto

package contractsv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetVersionRequest reads the service build identity and live mode.
type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescGZIP(), []int{0}
}

// GetVersionResponse is the service build identity plus the live masking mode.
type GetVersionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit  string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Date    string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	// mode is the live masking mode ("enforce" or "detect").
	Mode          string `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	StoreBackend  string `protobuf:"bytes,5,opt,name=store_backend,json=storeBackend,proto3" json:"store_backend,omitempty"`
	Topology      string `protobuf:"bytes,6,opt,name=topology,proto3" json:"topology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetVersionResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetVersionResponse) GetStoreBackend() string {
	if x != nil {
		return x.StoreBackend
	}
	return ""
}

func (x *GetVersionResponse) GetTopology() string {
	if x != nil {
		return x.Topology
	}
	return ""
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDesc = "" +
	"\n" +
	"Capi/proto/cloudru/guardrails/v1/service/contracts/get_version.proto\x12'cloudru.guardrails.v1.service.contracts\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x13\n" +
	"\x11GetVersionRequest\"\xaf\x01\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12#\n" +
	"\rstore_backend\x18\x05 \x01(\tR\fstoreBackend\x12\x1a\n" +
	"\btopology\x18\x06 \x01(\tR\btopologyBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_goTypes = []any{
	(*GetVersionRequest)(nil),  // 0: cloudru.guardrails.v1.service.contracts.GetVersionRequest
	(*GetVersionResponse)(nil), // 1: cloudru.guardrails.v1.service.contracts.GetVersionResponse
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_get_version_proto_depIdxs = nil
}
