// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/list_rules.proto

package contractsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListRulesRequest lists rules filtered by source.
type ListRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source selects which rules to return: "all" (default), "builtin" or "custom".
	Source        string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescGZIP(), []int{0}
}

func (x *ListRulesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// ListRulesResponse is the list of rules.
type ListRulesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rules         []*common.GuardrailRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescGZIP(), []int{1}
}

func (x *ListRulesResponse) GetRules() []*common.GuardrailRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDesc = "" +
	"\n" +
	"Bapi/proto/cloudru/guardrails/v1/service/contracts/list_rules.proto\x12'cloudru.guardrails.v1.service.contracts\x1a/proto/protovalidate/buf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1aCapi/proto/cloudru/guardrails/v1/service/common/guardrail_rule.proto\"\x82\x01\n" +
	"\x10ListRulesRequest\x12n\n" +
	"\x06source\x18\x01 \x01(\tBV\x92A624Rule source filter: all|builtin|custom (default all)\xbaH\x1ar\x18R\x00R\x03allR\abuiltinR\x06customR\x06source\"^\n" +
	"\x11ListRulesResponse\x12I\n" +
	"\x05rules\x18\x01 \x03(\v23.cloudru.guardrails.v1.service.common.GuardrailRuleR\x05rulesBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_goTypes = []any{
	(*ListRulesRequest)(nil),     // 0: cloudru.guardrails.v1.service.contracts.ListRulesRequest
	(*ListRulesResponse)(nil),    // 1: cloudru.guardrails.v1.service.contracts.ListRulesResponse
	(*common.GuardrailRule)(nil), // 2: cloudru.guardrails.v1.service.common.GuardrailRule
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_depIdxs = []int32{
	2, // 0: cloudru.guardrails.v1.service.contracts.ListRulesResponse.rules:type_name -> cloudru.guardrails.v1.service.common.GuardrailRule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_rules_proto_depIdxs = nil
}
