// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/list_audit_records.proto

package contractsv1

import (
	common "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListAuditRecordsRequest filters and paginates the masking audit trail. Zero
// values mean "any".
type ListAuditRecordsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Model    string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Path     string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RuleId   string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	DataType common.DataType        `protobuf:"varint,4,opt,name=data_type,json=dataType,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"data_type,omitempty"`
	Since    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	Until    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=until,proto3" json:"until,omitempty"`
	// limit is the page size; 0 uses the default, capped server-side.
	Limit int32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	// cursor is the opaque cursor from a previous response ("" = first page).
	Cursor        string `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditRecordsRequest) Reset() {
	*x = ListAuditRecordsRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditRecordsRequest) ProtoMessage() {}

func (x *ListAuditRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditRecordsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuditRecordsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListAuditRecordsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListAuditRecordsRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ListAuditRecordsRequest) GetDataType() common.DataType {
	if x != nil {
		return x.DataType
	}
	return common.DataType(0)
}

func (x *ListAuditRecordsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListAuditRecordsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ListAuditRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditRecordsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ListAuditRecordsResponse is one page of audit records.
type ListAuditRecordsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*common.AuditRecord  `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// next_cursor is empty when the listing is exhausted.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditRecordsResponse) Reset() {
	*x = ListAuditRecordsResponse{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditRecordsResponse) ProtoMessage() {}

func (x *ListAuditRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditRecordsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditRecordsResponse) GetRecords() []*common.AuditRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListAuditRecordsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDesc = "" +
	"\n" +
	"Japi/proto/cloudru/guardrails/v1/service/contracts/list_audit_records.proto\x12'cloudru.guardrails.v1.service.contracts\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1aAapi/proto/cloudru/guardrails/v1/service/common/audit_record.proto\x1a>api/proto/cloudru/guardrails/v1/service/common/data_type.proto\"\xbb\x02\n" +
	"\x17ListAuditRecordsRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12K\n" +
	"\tdata_type\x18\x04 \x01(\x0e2..cloudru.guardrails.v1.service.common.DataTypeR\bdataType\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\"\x88\x01\n" +
	"\x18ListAuditRecordsResponse\x12K\n" +
	"\arecords\x18\x01 \x03(\v21.cloudru.guardrails.v1.service.common.AuditRecordR\arecords\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursorBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_goTypes = []any{
	(*ListAuditRecordsRequest)(nil),  // 0: cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest
	(*ListAuditRecordsResponse)(nil), // 1: cloudru.guardrails.v1.service.contracts.ListAuditRecordsResponse
	(common.DataType)(0),             // 2: cloudru.guardrails.v1.service.common.DataType
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
	(*common.AuditRecord)(nil),       // 4: cloudru.guardrails.v1.service.common.AuditRecord
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_depIdxs = []int32{
	2, // 0: cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest.data_type:type_name -> cloudru.guardrails.v1.service.common.DataType
	3, // 1: cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest.since:type_name -> google.protobuf.Timestamp
	3, // 2: cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest.until:type_name -> google.protobuf.Timestamp
	4, // 3: cloudru.guardrails.v1.service.contracts.ListAuditRecordsResponse.records:type_name -> cloudru.guardrails.v1.service.common.AuditRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_list_audit_records_proto_depIdxs = nil
}
