// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/scan.proto

package contractsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScanRequest is a dry-run masking check. It reuses the production scan+mask
// pipeline but persists nothing and calls no upstream.
type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// texts are the sample inputs to scan (in order).
	Texts []string `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	// text is a single-sample convenience; merged into texts when texts is empty.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// data_types narrows the scan; empty means all known types.
	DataTypes []common.DataType `protobuf:"varint,3,rep,packed,name=data_types,json=dataTypes,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"data_types,omitempty"`
	// candidate_rule tests a not-yet-saved rule against the sample.
	CandidateRule *common.GuardrailRule `protobuf:"bytes,4,opt,name=candidate_rule,json=candidateRule,proto3" json:"candidate_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *ScanRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ScanRequest) GetDataTypes() []common.DataType {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *ScanRequest) GetCandidateRule() *common.GuardrailRule {
	if x != nil {
		return x.CandidateRule
	}
	return nil
}

// ScanResponse is the dry-run scan result. Nothing here is persisted.
type ScanResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaskedTexts        []string               `protobuf:"bytes,1,rep,name=masked_texts,json=maskedTexts,proto3" json:"masked_texts,omitempty"`
	TriggeredRuleIds   []string               `protobuf:"bytes,2,rep,name=triggered_rule_ids,json=triggeredRuleIds,proto3" json:"triggered_rule_ids,omitempty"`
	TriggeredDataTypes []common.DataType      `protobuf:"varint,3,rep,packed,name=triggered_data_types,json=triggeredDataTypes,proto3,enum=cloudru.guardrails.v1.service.common.DataType" json:"triggered_data_types,omitempty"`
	Placeholders       []*common.Placeholder  `protobuf:"bytes,4,rep,name=placeholders,proto3" json:"placeholders,omitempty"`
	// total_ms is the scan wall-clock time in milliseconds.
	TotalMs       int32 `protobuf:"varint,5,opt,name=total_ms,json=totalMs,proto3" json:"total_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetMaskedTexts() []string {
	if x != nil {
		return x.MaskedTexts
	}
	return nil
}

func (x *ScanResponse) GetTriggeredRuleIds() []string {
	if x != nil {
		return x.TriggeredRuleIds
	}
	return nil
}

func (x *ScanResponse) GetTriggeredDataTypes() []common.DataType {
	if x != nil {
		return x.TriggeredDataTypes
	}
	return nil
}

func (x *ScanResponse) GetPlaceholders() []*common.Placeholder {
	if x != nil {
		return x.Placeholders
	}
	return nil
}

func (x *ScanResponse) GetTotalMs() int32 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDesc = "" +
	"\n" +
	"<api/proto/cloudru/guardrails/v1/service/contracts/scan.proto\x12'cloudru.guardrails.v1.service.contracts\x1a/proto/protovalidate/buf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a>api/proto/cloudru/guardrails/v1/service/common/data_type.proto\x1aCapi/proto/cloudru/guardrails/v1/service/common/guardrail_rule.proto\x1a@api/proto/cloudru/guardrails/v1/service/common/placeholder.proto\"\xa3\x03\n" +
	"\vScanRequest\x120\n" +
	"\x05texts\x18\x01 \x03(\tB\x1a\x92A\x172\x15Sample inputs to scanR\x05texts\x12Q\n" +
	"\x04text\x18\x02 \x01(\tB=\x92A:28Single sample convenience; used only when texts is emptyR\x04text\x12\x87\x01\n" +
	"\n" +
	"data_types\x18\x03 \x03(\x0e2..cloudru.guardrails.v1.service.common.DataTypeB8\x92A523Limit the scan to these data types; empty means allR\tdataTypes\x12\x84\x01\n" +
	"\x0ecandidate_rule\x18\x04 \x01(\v23.cloudru.guardrails.v1.service.common.GuardrailRuleB(\x92A%2#Optional not-yet-saved rule to testR\rcandidateRule\"\xb3\x02\n" +
	"\fScanResponse\x12!\n" +
	"\fmasked_texts\x18\x01 \x03(\tR\vmaskedTexts\x12,\n" +
	"\x12triggered_rule_ids\x18\x02 \x03(\tR\x10triggeredRuleIds\x12`\n" +
	"\x14triggered_data_types\x18\x03 \x03(\x0e2..cloudru.guardrails.v1.service.common.DataTypeR\x12triggeredDataTypes\x12U\n" +
	"\fplaceholders\x18\x04 \x03(\v21.cloudru.guardrails.v1.service.common.PlaceholderR\fplaceholders\x12\x19\n" +
	"\btotal_ms\x18\x05 \x01(\x05R\atotalMsBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_goTypes = []any{
	(*ScanRequest)(nil),          // 0: cloudru.guardrails.v1.service.contracts.ScanRequest
	(*ScanResponse)(nil),         // 1: cloudru.guardrails.v1.service.contracts.ScanResponse
	(common.DataType)(0),         // 2: cloudru.guardrails.v1.service.common.DataType
	(*common.GuardrailRule)(nil), // 3: cloudru.guardrails.v1.service.common.GuardrailRule
	(*common.Placeholder)(nil),   // 4: cloudru.guardrails.v1.service.common.Placeholder
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_depIdxs = []int32{
	2, // 0: cloudru.guardrails.v1.service.contracts.ScanRequest.data_types:type_name -> cloudru.guardrails.v1.service.common.DataType
	3, // 1: cloudru.guardrails.v1.service.contracts.ScanRequest.candidate_rule:type_name -> cloudru.guardrails.v1.service.common.GuardrailRule
	2, // 2: cloudru.guardrails.v1.service.contracts.ScanResponse.triggered_data_types:type_name -> cloudru.guardrails.v1.service.common.DataType
	4, // 3: cloudru.guardrails.v1.service.contracts.ScanResponse.placeholders:type_name -> cloudru.guardrails.v1.service.common.Placeholder
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_scan_proto_depIdxs = nil
}
