// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/contracts/set_rule_enabled.proto

package contractsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetRuleEnabledRequest enables or disables one rule. This is the only
// mutation permitted on built-in rules.
type SetRuleEnabledRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RuleId string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// enabled is required: absence is rejected rather than defaulting to false.
	Enabled       *bool `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleEnabledRequest) Reset() {
	*x = SetRuleEnabledRequest{}
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleEnabledRequest) ProtoMessage() {}

func (x *SetRuleEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetRuleEnabledRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescGZIP(), []int{0}
}

func (x *SetRuleEnabledRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *SetRuleEnabledRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

var File_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDesc = "" +
	"\n" +
	"Hapi/proto/cloudru/guardrails/v1/service/contracts/set_rule_enabled.proto\x12'cloudru.guardrails.v1.service.contracts\x1a/proto/protovalidate/buf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9a\x01\n" +
	"\x15SetRuleEnabledRequest\x124\n" +
	"\arule_id\x18\x01 \x01(\tB\x1b\x92A\x112\x0fRule identifier\xbaH\x04r\x02\x10\x01R\x06ruleId\x12?\n" +
	"\aenabled\x18\x02 \x01(\bB \x92A\x172\x15Desired enabled state\xbaH\x03\xc8\x01\x01H\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledBzZxgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts;contractsv1b\x06proto3"

var (
	file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescOnce sync.Once
	file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescData []byte
)

func file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescGZIP() []byte {
	file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescOnce.Do(func() {
		file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDesc)))
	})
	return file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDescData
}

var file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_goTypes = []any{
	(*SetRuleEnabledRequest)(nil), // 0: cloudru.guardrails.v1.service.contracts.SetRuleEnabledRequest
}
var file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto != nil {
		return
	}
	file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_depIdxs,
		MessageInfos:      file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_msgTypes,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_contracts_set_rule_enabled_proto_depIdxs = nil
}
