// Code generated by MockGen. DO NOT EDIT.
// Source: scanner.go
//
// Generated by this command:
//
//	mockgen -source=scanner.go -destination=mock_test.go -package=sensitive_test
//

// Package sensitive_test is a generated GoMock package.
package sensitive_test

import (
	reflect "reflect"

	registry "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/guardrails/regex/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// GetCompiledRulesByRuleIDs mocks base method.
func (m *MockRegistry) GetCompiledRulesByRuleIDs(ruleIDs []string) []registry.CompiledRule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompiledRulesByRuleIDs", ruleIDs)
	ret0, _ := ret[0].([]registry.CompiledRule)
	return ret0
}

// GetCompiledRulesByRuleIDs indicates an expected call of GetCompiledRulesByRuleIDs.
func (mr *MockRegistryMockRecorder) GetCompiledRulesByRuleIDs(ruleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompiledRulesByRuleIDs", reflect.TypeOf((*MockRegistry)(nil).GetCompiledRulesByRuleIDs), ruleIDs)
}
