// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock_test.go -package=demask_test
//

// Package demask_test is a generated GoMock package.
package demask_test

import (
	reflect "reflect"

	placeholder "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/guardrails/regex/scanners/placeholder"
	gomock "go.uber.org/mock/gomock"
)

// MockPlaceholderScanner is a mock of PlaceholderScanner interface.
type MockPlaceholderScanner struct {
	ctrl     *gomock.Controller
	recorder *MockPlaceholderScannerMockRecorder
	isgomock struct{}
}

// MockPlaceholderScannerMockRecorder is the mock recorder for MockPlaceholderScanner.
type MockPlaceholderScannerMockRecorder struct {
	mock *MockPlaceholderScanner
}

// NewMockPlaceholderScanner creates a new mock instance.
func NewMockPlaceholderScanner(ctrl *gomock.Controller) *MockPlaceholderScanner {
	mock := &MockPlaceholderScanner{ctrl: ctrl}
	mock.recorder = &MockPlaceholderScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaceholderScanner) EXPECT() *MockPlaceholderScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockPlaceholderScanner) Scan(text string, ruleIDs []string) ([]placeholder.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", text, ruleIDs)
	ret0, _ := ret[0].([]placeholder.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockPlaceholderScannerMockRecorder) Scan(text, ruleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockPlaceholderScanner)(nil).Scan), text, ruleIDs)
}

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// GetMaxPlaceholderLenByRuleIDs mocks base method.
func (m *MockRegistry) GetMaxPlaceholderLenByRuleIDs(ruleIDs ...string) int {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range ruleIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMaxPlaceholderLenByRuleIDs", varargs...)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxPlaceholderLenByRuleIDs indicates an expected call of GetMaxPlaceholderLenByRuleIDs.
func (mr *MockRegistryMockRecorder) GetMaxPlaceholderLenByRuleIDs(ruleIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPlaceholderLenByRuleIDs", reflect.TypeOf((*MockRegistry)(nil).GetMaxPlaceholderLenByRuleIDs), ruleIDs...)
}
