apiVersion: v1
kind: Service
metadata:
  name: guardrails-llm-filter-extproc
  labels:
    app: guardrails-llm-filter-extproc
spec:
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
    - name: health
      port: 9005
      targetPort: 9005
    - name: api
      port: 9080
      targetPort: 9080
    - name: mgmt-grpc
      port: 9090
      targetPort: 9090
    - name: metrics
      port: 9091
      targetPort: 9091
  selector:
    app: guardrails-llm-filter-extproc
  type: ClusterIP
