// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_test.go -package=list_test
//

// Package list_test is a generated GoMock package.
package list_test

import (
	context "context"
	reflect "reflect"

	list "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/internal/usecases/rules/list"
	rule "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/guardrails/regex/rule"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandHandler is a mock of CommandHandler interface.
type MockCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommandHandlerMockRecorder
	isgomock struct{}
}

// MockCommandHandlerMockRecorder is the mock recorder for MockCommandHandler.
type MockCommandHandlerMockRecorder struct {
	mock *MockCommandHandler
}

// NewMockCommandHandler creates a new mock instance.
func NewMockCommandHandler(ctrl *gomock.Controller) *MockCommandHandler {
	mock := &MockCommandHandler{ctrl: ctrl}
	mock.recorder = &MockCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandHandler) EXPECT() *MockCommandHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockCommandHandler) Handle(ctx context.Context, cmd list.Command) (list.CommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, cmd)
	ret0, _ := ret[0].(list.CommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCommandHandlerMockRecorder) Handle(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCommandHandler)(nil).Handle), ctx, cmd)
}

// MockRuleStore is a mock of RuleStore interface.
type MockRuleStore struct {
	ctrl     *gomock.Controller
	recorder *MockRuleStoreMockRecorder
	isgomock struct{}
}

// MockRuleStoreMockRecorder is the mock recorder for MockRuleStore.
type MockRuleStoreMockRecorder struct {
	mock *MockRuleStore
}

// NewMockRuleStore creates a new mock instance.
func NewMockRuleStore(ctrl *gomock.Controller) *MockRuleStore {
	mock := &MockRuleStore{ctrl: ctrl}
	mock.recorder = &MockRuleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleStore) EXPECT() *MockRuleStoreMockRecorder {
	return m.recorder
}

// ListDisabledRuleIDs mocks base method.
func (m *MockRuleStore) ListDisabledRuleIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDisabledRuleIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDisabledRuleIDs indicates an expected call of ListDisabledRuleIDs.
func (mr *MockRuleStoreMockRecorder) ListDisabledRuleIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDisabledRuleIDs", reflect.TypeOf((*MockRuleStore)(nil).ListDisabledRuleIDs), ctx)
}

// ListRules mocks base method.
func (m *MockRuleStore) ListRules(ctx context.Context) ([]rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockRuleStoreMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockRuleStore)(nil).ListRules), ctx)
}

// MockBuiltins is a mock of Builtins interface.
type MockBuiltins struct {
	ctrl     *gomock.Controller
	recorder *MockBuiltinsMockRecorder
	isgomock struct{}
}

// MockBuiltinsMockRecorder is the mock recorder for MockBuiltins.
type MockBuiltinsMockRecorder struct {
	mock *MockBuiltins
}

// NewMockBuiltins creates a new mock instance.
func NewMockBuiltins(ctrl *gomock.Controller) *MockBuiltins {
	mock := &MockBuiltins{ctrl: ctrl}
	mock.recorder = &MockBuiltinsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuiltins) EXPECT() *MockBuiltinsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockBuiltins) List() []rule.Rule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]rule.Rule)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockBuiltinsMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBuiltins)(nil).List))
}
