// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/service.proto

package servicev1

import (
	common "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common"
	contracts "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_cloudru_guardrails_v1_service_service_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_service_proto_rawDesc = "" +
	"\n" +
	"5api/proto/cloudru/guardrails/v1/service/service.proto\x12\x1dcloudru.guardrails.v1.service\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1aCapi/proto/cloudru/guardrails/v1/service/common/guardrail_rule.proto\x1a=api/proto/cloudru/guardrails/v1/service/common/settings.proto\x1aAapi/proto/cloudru/guardrails/v1/service/common/audit_record.proto\x1aBapi/proto/cloudru/guardrails/v1/service/contracts/list_rules.proto\x1a@api/proto/cloudru/guardrails/v1/service/contracts/get_rule.proto\x1aHapi/proto/cloudru/guardrails/v1/service/contracts/set_rule_enabled.proto\x1aNapi/proto/cloudru/guardrails/v1/service/contracts/bulk_set_rules_enabled.proto\x1aCapi/proto/cloudru/guardrails/v1/service/contracts/delete_rule.proto\x1aDapi/proto/cloudru/guardrails/v1/service/contracts/get_settings.proto\x1aFapi/proto/cloudru/guardrails/v1/service/contracts/get_data_types.proto\x1a<api/proto/cloudru/guardrails/v1/service/contracts/scan.proto\x1aJapi/proto/cloudru/guardrails/v1/service/contracts/list_audit_records.proto\x1aHapi/proto/cloudru/guardrails/v1/service/contracts/get_audit_record.proto\x1aCapi/proto/cloudru/guardrails/v1/service/contracts/get_version.proto2\xfc\x15\n" +
	"\rGuardrailsApi\x12\xb0\x01\n" +
	"\tListRules\x129.cloudru.guardrails.v1.service.contracts.ListRulesRequest\x1a:.cloudru.guardrails.v1.service.contracts.ListRulesResponse\",\x92A\x18\n" +
	"\n" +
	"Guardrails\x12\n" +
	"List rules\x82\xd3\xe4\x93\x02\v\x12\t/v1/rules\x12\xaf\x01\n" +
	"\n" +
	"CreateRule\x123.cloudru.guardrails.v1.service.common.GuardrailRule\x1a3.cloudru.guardrails.v1.service.common.GuardrailRule\"7\x92A \n" +
	"\n" +
	"Guardrails\x12\x12Create custom rule\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/rules\x12\xad\x01\n" +
	"\aGetRule\x127.cloudru.guardrails.v1.service.contracts.GetRuleRequest\x1a3.cloudru.guardrails.v1.service.common.GuardrailRule\"4\x92A\x16\n" +
	"\n" +
	"Guardrails\x12\bGet rule\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/rules/{rule_id}\x12\xb9\x01\n" +
	"\n" +
	"UpdateRule\x123.cloudru.guardrails.v1.service.common.GuardrailRule\x1a3.cloudru.guardrails.v1.service.common.GuardrailRule\"A\x92A \n" +
	"\n" +
	"Guardrails\x12\x12Update custom rule\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/rules/{rule_id}\x12\xce\x01\n" +
	"\x0eSetRuleEnabled\x12>.cloudru.guardrails.v1.service.contracts.SetRuleEnabledRequest\x1a3.cloudru.guardrails.v1.service.common.GuardrailRule\"G\x92A&\n" +
	"\n" +
	"Guardrails\x12\x18Enable or disable a rule\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/rules/{rule_id}\x12\xe3\x01\n" +
	"\x13BulkSetRulesEnabled\x12C.cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledRequest\x1aD.cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledResponse\"A\x92A*\n" +
	"\n" +
	"Guardrails\x12\x1cBulk enable or disable rules\x82\xd3\xe4\x93\x02\x0e:\x01*2\t/v1/rules\x12\xa0\x01\n" +
	"\n" +
	"DeleteRule\x12:.cloudru.guardrails.v1.service.contracts.DeleteRuleRequest\x1a\x16.google.protobuf.Empty\">\x92A \n" +
	"\n" +
	"Guardrails\x12\x12Delete custom rule\x82\xd3\xe4\x93\x02\x15*\x13/v1/rules/{rule_id}\x12\xbe\x01\n" +
	"\vGetSettings\x12;.cloudru.guardrails.v1.service.contracts.GetSettingsRequest\x1a8.cloudru.guardrails.v1.service.common.GuardrailsSettings\"8\x92A!\n" +
	"\n" +
	"Guardrails\x12\x13Get global settings\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/settings\x12\xc4\x01\n" +
	"\x0eUpdateSettings\x128.cloudru.guardrails.v1.service.common.GuardrailsSettings\x1a8.cloudru.guardrails.v1.service.common.GuardrailsSettings\">\x92A$\n" +
	"\n" +
	"Guardrails\x12\x16Update global settings\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/v1/settings\x12\xc3\x01\n" +
	"\fGetDataTypes\x12<.cloudru.guardrails.v1.service.contracts.GetDataTypesRequest\x1a=.cloudru.guardrails.v1.service.contracts.GetDataTypesResponse\"6\x92A\x1d\n" +
	"\n" +
	"Guardrails\x12\x0fList data types\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/data-types\x12\xad\x01\n" +
	"\x04Scan\x124.cloudru.guardrails.v1.service.contracts.ScanRequest\x1a5.cloudru.guardrails.v1.service.contracts.ScanResponse\"8\x92A\"\n" +
	"\n" +
	"Guardrails\x12\x14Dry-run masking scan\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/scan\x12\xd5\x01\n" +
	"\x10ListAuditRecords\x12@.cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest\x1aA.cloudru.guardrails.v1.service.contracts.ListAuditRecordsResponse\"<\x92A \n" +
	"\n" +
	"Guardrails\x12\x12List audit records\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/audit/records\x12\xcc\x01\n" +
	"\x0eGetAuditRecord\x12>.cloudru.guardrails.v1.service.contracts.GetAuditRecordRequest\x1a1.cloudru.guardrails.v1.service.common.AuditRecord\"G\x92A\x1e\n" +
	"\n" +
	"Guardrails\x12\x10Get audit record\x82\xd3\xe4\x93\x02 \x12\x1e/v1/audit/records/{request_id}\x12\xb6\x01\n" +
	"\n" +
	"GetVersion\x12:.cloudru.guardrails.v1.service.contracts.GetVersionRequest\x1a;.cloudru.guardrails.v1.service.contracts.GetVersionResponse\"/\x92A\x19\n" +
	"\n" +
	"Guardrails\x12\vGet version\x82\xd3\xe4\x93\x02\r\x12\v/v1/version\x1ab\x92A_\n" +
	"\n" +
	"Guardrails\x12QCustom rule CRUD, global settings, data-type discovery and dry-run masking checksBnZlgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service;servicev1b\x06proto3"

var file_api_proto_cloudru_guardrails_v1_service_service_proto_goTypes = []any{
	(*contracts.ListRulesRequest)(nil),            // 0: cloudru.guardrails.v1.service.contracts.ListRulesRequest
	(*common.GuardrailRule)(nil),                  // 1: cloudru.guardrails.v1.service.common.GuardrailRule
	(*contracts.GetRuleRequest)(nil),              // 2: cloudru.guardrails.v1.service.contracts.GetRuleRequest
	(*contracts.SetRuleEnabledRequest)(nil),       // 3: cloudru.guardrails.v1.service.contracts.SetRuleEnabledRequest
	(*contracts.BulkSetRulesEnabledRequest)(nil),  // 4: cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledRequest
	(*contracts.DeleteRuleRequest)(nil),           // 5: cloudru.guardrails.v1.service.contracts.DeleteRuleRequest
	(*contracts.GetSettingsRequest)(nil),          // 6: cloudru.guardrails.v1.service.contracts.GetSettingsRequest
	(*common.GuardrailsSettings)(nil),             // 7: cloudru.guardrails.v1.service.common.GuardrailsSettings
	(*contracts.GetDataTypesRequest)(nil),         // 8: cloudru.guardrails.v1.service.contracts.GetDataTypesRequest
	(*contracts.ScanRequest)(nil),                 // 9: cloudru.guardrails.v1.service.contracts.ScanRequest
	(*contracts.ListAuditRecordsRequest)(nil),     // 10: cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest
	(*contracts.GetAuditRecordRequest)(nil),       // 11: cloudru.guardrails.v1.service.contracts.GetAuditRecordRequest
	(*contracts.GetVersionRequest)(nil),           // 12: cloudru.guardrails.v1.service.contracts.GetVersionRequest
	(*contracts.ListRulesResponse)(nil),           // 13: cloudru.guardrails.v1.service.contracts.ListRulesResponse
	(*contracts.BulkSetRulesEnabledResponse)(nil), // 14: cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledResponse
	(*emptypb.Empty)(nil),                         // 15: google.protobuf.Empty
	(*contracts.GetDataTypesResponse)(nil),        // 16: cloudru.guardrails.v1.service.contracts.GetDataTypesResponse
	(*contracts.ScanResponse)(nil),                // 17: cloudru.guardrails.v1.service.contracts.ScanResponse
	(*contracts.ListAuditRecordsResponse)(nil),    // 18: cloudru.guardrails.v1.service.contracts.ListAuditRecordsResponse
	(*common.AuditRecord)(nil),                    // 19: cloudru.guardrails.v1.service.common.AuditRecord
	(*contracts.GetVersionResponse)(nil),          // 20: cloudru.guardrails.v1.service.contracts.GetVersionResponse
}
var file_api_proto_cloudru_guardrails_v1_service_service_proto_depIdxs = []int32{
	0,  // 0: cloudru.guardrails.v1.service.GuardrailsApi.ListRules:input_type -> cloudru.guardrails.v1.service.contracts.ListRulesRequest
	1,  // 1: cloudru.guardrails.v1.service.GuardrailsApi.CreateRule:input_type -> cloudru.guardrails.v1.service.common.GuardrailRule
	2,  // 2: cloudru.guardrails.v1.service.GuardrailsApi.GetRule:input_type -> cloudru.guardrails.v1.service.contracts.GetRuleRequest
	1,  // 3: cloudru.guardrails.v1.service.GuardrailsApi.UpdateRule:input_type -> cloudru.guardrails.v1.service.common.GuardrailRule
	3,  // 4: cloudru.guardrails.v1.service.GuardrailsApi.SetRuleEnabled:input_type -> cloudru.guardrails.v1.service.contracts.SetRuleEnabledRequest
	4,  // 5: cloudru.guardrails.v1.service.GuardrailsApi.BulkSetRulesEnabled:input_type -> cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledRequest
	5,  // 6: cloudru.guardrails.v1.service.GuardrailsApi.DeleteRule:input_type -> cloudru.guardrails.v1.service.contracts.DeleteRuleRequest
	6,  // 7: cloudru.guardrails.v1.service.GuardrailsApi.GetSettings:input_type -> cloudru.guardrails.v1.service.contracts.GetSettingsRequest
	7,  // 8: cloudru.guardrails.v1.service.GuardrailsApi.UpdateSettings:input_type -> cloudru.guardrails.v1.service.common.GuardrailsSettings
	8,  // 9: cloudru.guardrails.v1.service.GuardrailsApi.GetDataTypes:input_type -> cloudru.guardrails.v1.service.contracts.GetDataTypesRequest
	9,  // 10: cloudru.guardrails.v1.service.GuardrailsApi.Scan:input_type -> cloudru.guardrails.v1.service.contracts.ScanRequest
	10, // 11: cloudru.guardrails.v1.service.GuardrailsApi.ListAuditRecords:input_type -> cloudru.guardrails.v1.service.contracts.ListAuditRecordsRequest
	11, // 12: cloudru.guardrails.v1.service.GuardrailsApi.GetAuditRecord:input_type -> cloudru.guardrails.v1.service.contracts.GetAuditRecordRequest
	12, // 13: cloudru.guardrails.v1.service.GuardrailsApi.GetVersion:input_type -> cloudru.guardrails.v1.service.contracts.GetVersionRequest
	13, // 14: cloudru.guardrails.v1.service.GuardrailsApi.ListRules:output_type -> cloudru.guardrails.v1.service.contracts.ListRulesResponse
	1,  // 15: cloudru.guardrails.v1.service.GuardrailsApi.CreateRule:output_type -> cloudru.guardrails.v1.service.common.GuardrailRule
	1,  // 16: cloudru.guardrails.v1.service.GuardrailsApi.GetRule:output_type -> cloudru.guardrails.v1.service.common.GuardrailRule
	1,  // 17: cloudru.guardrails.v1.service.GuardrailsApi.UpdateRule:output_type -> cloudru.guardrails.v1.service.common.GuardrailRule
	1,  // 18: cloudru.guardrails.v1.service.GuardrailsApi.SetRuleEnabled:output_type -> cloudru.guardrails.v1.service.common.GuardrailRule
	14, // 19: cloudru.guardrails.v1.service.GuardrailsApi.BulkSetRulesEnabled:output_type -> cloudru.guardrails.v1.service.contracts.BulkSetRulesEnabledResponse
	15, // 20: cloudru.guardrails.v1.service.GuardrailsApi.DeleteRule:output_type -> google.protobuf.Empty
	7,  // 21: cloudru.guardrails.v1.service.GuardrailsApi.GetSettings:output_type -> cloudru.guardrails.v1.service.common.GuardrailsSettings
	7,  // 22: cloudru.guardrails.v1.service.GuardrailsApi.UpdateSettings:output_type -> cloudru.guardrails.v1.service.common.GuardrailsSettings
	16, // 23: cloudru.guardrails.v1.service.GuardrailsApi.GetDataTypes:output_type -> cloudru.guardrails.v1.service.contracts.GetDataTypesResponse
	17, // 24: cloudru.guardrails.v1.service.GuardrailsApi.Scan:output_type -> cloudru.guardrails.v1.service.contracts.ScanResponse
	18, // 25: cloudru.guardrails.v1.service.GuardrailsApi.ListAuditRecords:output_type -> cloudru.guardrails.v1.service.contracts.ListAuditRecordsResponse
	19, // 26: cloudru.guardrails.v1.service.GuardrailsApi.GetAuditRecord:output_type -> cloudru.guardrails.v1.service.common.AuditRecord
	20, // 27: cloudru.guardrails.v1.service.GuardrailsApi.GetVersion:output_type -> cloudru.guardrails.v1.service.contracts.GetVersionResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_service_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_service_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_service_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_service_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_service_proto_depIdxs,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_service_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_service_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_service_proto_depIdxs = nil
}
