// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/proto/cloudru/guardrails/v1/service/service.proto

package servicev1

import (
	context "context"
	common "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/common"
	contracts "github.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service/contracts"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuardrailsApi_ListRules_FullMethodName           = "/cloudru.guardrails.v1.service.GuardrailsApi/ListRules"
	GuardrailsApi_CreateRule_FullMethodName          = "/cloudru.guardrails.v1.service.GuardrailsApi/CreateRule"
	GuardrailsApi_GetRule_FullMethodName             = "/cloudru.guardrails.v1.service.GuardrailsApi/GetRule"
	GuardrailsApi_UpdateRule_FullMethodName          = "/cloudru.guardrails.v1.service.GuardrailsApi/UpdateRule"
	GuardrailsApi_SetRuleEnabled_FullMethodName      = "/cloudru.guardrails.v1.service.GuardrailsApi/SetRuleEnabled"
	GuardrailsApi_BulkSetRulesEnabled_FullMethodName = "/cloudru.guardrails.v1.service.GuardrailsApi/BulkSetRulesEnabled"
	GuardrailsApi_DeleteRule_FullMethodName          = "/cloudru.guardrails.v1.service.GuardrailsApi/DeleteRule"
	GuardrailsApi_GetSettings_FullMethodName         = "/cloudru.guardrails.v1.service.GuardrailsApi/GetSettings"
	GuardrailsApi_UpdateSettings_FullMethodName      = "/cloudru.guardrails.v1.service.GuardrailsApi/UpdateSettings"
	GuardrailsApi_GetDataTypes_FullMethodName        = "/cloudru.guardrails.v1.service.GuardrailsApi/GetDataTypes"
	GuardrailsApi_Scan_FullMethodName                = "/cloudru.guardrails.v1.service.GuardrailsApi/Scan"
	GuardrailsApi_ListAuditRecords_FullMethodName    = "/cloudru.guardrails.v1.service.GuardrailsApi/ListAuditRecords"
	GuardrailsApi_GetAuditRecord_FullMethodName      = "/cloudru.guardrails.v1.service.GuardrailsApi/GetAuditRecord"
	GuardrailsApi_GetVersion_FullMethodName          = "/cloudru.guardrails.v1.service.GuardrailsApi/GetVersion"
)

// GuardrailsApiClient is the client API for GuardrailsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GuardrailsApi is the management API for the standalone guardrails service.
// It mirrors the previous hand-rolled REST config API 1:1 via grpc-gateway.
type GuardrailsApiClient interface {
	// ListRules returns built-in and/or custom rules.
	ListRules(ctx context.Context, in *contracts.ListRulesRequest, opts ...grpc.CallOption) (*contracts.ListRulesResponse, error)
	// CreateRule creates a custom rule.
	CreateRule(ctx context.Context, in *common.GuardrailRule, opts ...grpc.CallOption) (*common.GuardrailRule, error)
	// GetRule reads one rule by ID.
	GetRule(ctx context.Context, in *contracts.GetRuleRequest, opts ...grpc.CallOption) (*common.GuardrailRule, error)
	// UpdateRule replaces an existing custom rule.
	UpdateRule(ctx context.Context, in *common.GuardrailRule, opts ...grpc.CallOption) (*common.GuardrailRule, error)
	// SetRuleEnabled enables or disables one rule (the only mutation allowed on
	// built-in rules).
	SetRuleEnabled(ctx context.Context, in *contracts.SetRuleEnabledRequest, opts ...grpc.CallOption) (*common.GuardrailRule, error)
	// BulkSetRulesEnabled enables or disables many rules in one best-effort call.
	BulkSetRulesEnabled(ctx context.Context, in *contracts.BulkSetRulesEnabledRequest, opts ...grpc.CallOption) (*contracts.BulkSetRulesEnabledResponse, error)
	// DeleteRule removes a custom rule by ID.
	DeleteRule(ctx context.Context, in *contracts.DeleteRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSettings reads the global guardrails settings.
	GetSettings(ctx context.Context, in *contracts.GetSettingsRequest, opts ...grpc.CallOption) (*common.GuardrailsSettings, error)
	// UpdateSettings replaces the global guardrails settings.
	UpdateSettings(ctx context.Context, in *common.GuardrailsSettings, opts ...grpc.CallOption) (*common.GuardrailsSettings, error)
	// GetDataTypes lists the toggleable data-type groups plus CUSTOM.
	GetDataTypes(ctx context.Context, in *contracts.GetDataTypesRequest, opts ...grpc.CallOption) (*contracts.GetDataTypesResponse, error)
	// Scan runs a dry-run masking check on sample text(s).
	Scan(ctx context.Context, in *contracts.ScanRequest, opts ...grpc.CallOption) (*contracts.ScanResponse, error)
	// ListAuditRecords lists masking audit records (audit trail must be enabled).
	ListAuditRecords(ctx context.Context, in *contracts.ListAuditRecordsRequest, opts ...grpc.CallOption) (*contracts.ListAuditRecordsResponse, error)
	// GetAuditRecord reads one masking audit record by request ID.
	GetAuditRecord(ctx context.Context, in *contracts.GetAuditRecordRequest, opts ...grpc.CallOption) (*common.AuditRecord, error)
	// GetVersion reports the service build identity and live masking mode.
	GetVersion(ctx context.Context, in *contracts.GetVersionRequest, opts ...grpc.CallOption) (*contracts.GetVersionResponse, error)
}

type guardrailsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGuardrailsApiClient(cc grpc.ClientConnInterface) GuardrailsApiClient {
	return &guardrailsApiClient{cc}
}

func (c *guardrailsApiClient) ListRules(ctx context.Context, in *contracts.ListRulesRequest, opts ...grpc.CallOption) (*contracts.ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(contracts.ListRulesResponse)
	err := c.cc.Invoke(ctx, GuardrailsApi_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) CreateRule(ctx context.Context, in *common.GuardrailRule, opts ...grpc.CallOption) (*common.GuardrailRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.GuardrailRule)
	err := c.cc.Invoke(ctx, GuardrailsApi_CreateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) GetRule(ctx context.Context, in *contracts.GetRuleRequest, opts ...grpc.CallOption) (*common.GuardrailRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.GuardrailRule)
	err := c.cc.Invoke(ctx, GuardrailsApi_GetRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) UpdateRule(ctx context.Context, in *common.GuardrailRule, opts ...grpc.CallOption) (*common.GuardrailRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.GuardrailRule)
	err := c.cc.Invoke(ctx, GuardrailsApi_UpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) SetRuleEnabled(ctx context.Context, in *contracts.SetRuleEnabledRequest, opts ...grpc.CallOption) (*common.GuardrailRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.GuardrailRule)
	err := c.cc.Invoke(ctx, GuardrailsApi_SetRuleEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) BulkSetRulesEnabled(ctx context.Context, in *contracts.BulkSetRulesEnabledRequest, opts ...grpc.CallOption) (*contracts.BulkSetRulesEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(contracts.BulkSetRulesEnabledResponse)
	err := c.cc.Invoke(ctx, GuardrailsApi_BulkSetRulesEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) DeleteRule(ctx context.Context, in *contracts.DeleteRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GuardrailsApi_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) GetSettings(ctx context.Context, in *contracts.GetSettingsRequest, opts ...grpc.CallOption) (*common.GuardrailsSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.GuardrailsSettings)
	err := c.cc.Invoke(ctx, GuardrailsApi_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) UpdateSettings(ctx context.Context, in *common.GuardrailsSettings, opts ...grpc.CallOption) (*common.GuardrailsSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.GuardrailsSettings)
	err := c.cc.Invoke(ctx, GuardrailsApi_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) GetDataTypes(ctx context.Context, in *contracts.GetDataTypesRequest, opts ...grpc.CallOption) (*contracts.GetDataTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(contracts.GetDataTypesResponse)
	err := c.cc.Invoke(ctx, GuardrailsApi_GetDataTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) Scan(ctx context.Context, in *contracts.ScanRequest, opts ...grpc.CallOption) (*contracts.ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(contracts.ScanResponse)
	err := c.cc.Invoke(ctx, GuardrailsApi_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) ListAuditRecords(ctx context.Context, in *contracts.ListAuditRecordsRequest, opts ...grpc.CallOption) (*contracts.ListAuditRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(contracts.ListAuditRecordsResponse)
	err := c.cc.Invoke(ctx, GuardrailsApi_ListAuditRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) GetAuditRecord(ctx context.Context, in *contracts.GetAuditRecordRequest, opts ...grpc.CallOption) (*common.AuditRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.AuditRecord)
	err := c.cc.Invoke(ctx, GuardrailsApi_GetAuditRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardrailsApiClient) GetVersion(ctx context.Context, in *contracts.GetVersionRequest, opts ...grpc.CallOption) (*contracts.GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(contracts.GetVersionResponse)
	err := c.cc.Invoke(ctx, GuardrailsApi_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardrailsApiServer is the server API for GuardrailsApi service.
// All implementations should embed UnimplementedGuardrailsApiServer
// for forward compatibility.
//
// GuardrailsApi is the management API for the standalone guardrails service.
// It mirrors the previous hand-rolled REST config API 1:1 via grpc-gateway.
type GuardrailsApiServer interface {
	// ListRules returns built-in and/or custom rules.
	ListRules(context.Context, *contracts.ListRulesRequest) (*contracts.ListRulesResponse, error)
	// CreateRule creates a custom rule.
	CreateRule(context.Context, *common.GuardrailRule) (*common.GuardrailRule, error)
	// GetRule reads one rule by ID.
	GetRule(context.Context, *contracts.GetRuleRequest) (*common.GuardrailRule, error)
	// UpdateRule replaces an existing custom rule.
	UpdateRule(context.Context, *common.GuardrailRule) (*common.GuardrailRule, error)
	// SetRuleEnabled enables or disables one rule (the only mutation allowed on
	// built-in rules).
	SetRuleEnabled(context.Context, *contracts.SetRuleEnabledRequest) (*common.GuardrailRule, error)
	// BulkSetRulesEnabled enables or disables many rules in one best-effort call.
	BulkSetRulesEnabled(context.Context, *contracts.BulkSetRulesEnabledRequest) (*contracts.BulkSetRulesEnabledResponse, error)
	// DeleteRule removes a custom rule by ID.
	DeleteRule(context.Context, *contracts.DeleteRuleRequest) (*emptypb.Empty, error)
	// GetSettings reads the global guardrails settings.
	GetSettings(context.Context, *contracts.GetSettingsRequest) (*common.GuardrailsSettings, error)
	// UpdateSettings replaces the global guardrails settings.
	UpdateSettings(context.Context, *common.GuardrailsSettings) (*common.GuardrailsSettings, error)
	// GetDataTypes lists the toggleable data-type groups plus CUSTOM.
	GetDataTypes(context.Context, *contracts.GetDataTypesRequest) (*contracts.GetDataTypesResponse, error)
	// Scan runs a dry-run masking check on sample text(s).
	Scan(context.Context, *contracts.ScanRequest) (*contracts.ScanResponse, error)
	// ListAuditRecords lists masking audit records (audit trail must be enabled).
	ListAuditRecords(context.Context, *contracts.ListAuditRecordsRequest) (*contracts.ListAuditRecordsResponse, error)
	// GetAuditRecord reads one masking audit record by request ID.
	GetAuditRecord(context.Context, *contracts.GetAuditRecordRequest) (*common.AuditRecord, error)
	// GetVersion reports the service build identity and live masking mode.
	GetVersion(context.Context, *contracts.GetVersionRequest) (*contracts.GetVersionResponse, error)
}

// UnimplementedGuardrailsApiServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuardrailsApiServer struct{}

func (UnimplementedGuardrailsApiServer) ListRules(context.Context, *contracts.ListRulesRequest) (*contracts.ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedGuardrailsApiServer) CreateRule(context.Context, *common.GuardrailRule) (*common.GuardrailRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRule not implemented")
}
func (UnimplementedGuardrailsApiServer) GetRule(context.Context, *contracts.GetRuleRequest) (*common.GuardrailRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRule not implemented")
}
func (UnimplementedGuardrailsApiServer) UpdateRule(context.Context, *common.GuardrailRule) (*common.GuardrailRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRule not implemented")
}
func (UnimplementedGuardrailsApiServer) SetRuleEnabled(context.Context, *contracts.SetRuleEnabledRequest) (*common.GuardrailRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRuleEnabled not implemented")
}
func (UnimplementedGuardrailsApiServer) BulkSetRulesEnabled(context.Context, *contracts.BulkSetRulesEnabledRequest) (*contracts.BulkSetRulesEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkSetRulesEnabled not implemented")
}
func (UnimplementedGuardrailsApiServer) DeleteRule(context.Context, *contracts.DeleteRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedGuardrailsApiServer) GetSettings(context.Context, *contracts.GetSettingsRequest) (*common.GuardrailsSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedGuardrailsApiServer) UpdateSettings(context.Context, *common.GuardrailsSettings) (*common.GuardrailsSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedGuardrailsApiServer) GetDataTypes(context.Context, *contracts.GetDataTypesRequest) (*contracts.GetDataTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataTypes not implemented")
}
func (UnimplementedGuardrailsApiServer) Scan(context.Context, *contracts.ScanRequest) (*contracts.ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedGuardrailsApiServer) ListAuditRecords(context.Context, *contracts.ListAuditRecordsRequest) (*contracts.ListAuditRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuditRecords not implemented")
}
func (UnimplementedGuardrailsApiServer) GetAuditRecord(context.Context, *contracts.GetAuditRecordRequest) (*common.AuditRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditRecord not implemented")
}
func (UnimplementedGuardrailsApiServer) GetVersion(context.Context, *contracts.GetVersionRequest) (*contracts.GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedGuardrailsApiServer) testEmbeddedByValue() {}

// UnsafeGuardrailsApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuardrailsApiServer will
// result in compilation errors.
type UnsafeGuardrailsApiServer interface {
	mustEmbedUnimplementedGuardrailsApiServer()
}

func RegisterGuardrailsApiServer(s grpc.ServiceRegistrar, srv GuardrailsApiServer) {
	// If the following call pancis, it indicates UnimplementedGuardrailsApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuardrailsApi_ServiceDesc, srv)
}

func _GuardrailsApi_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).ListRules(ctx, req.(*contracts.ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.GuardrailRule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_CreateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).CreateRule(ctx, req.(*common.GuardrailRule))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_GetRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).GetRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_GetRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).GetRule(ctx, req.(*contracts.GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_UpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.GuardrailRule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).UpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_UpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).UpdateRule(ctx, req.(*common.GuardrailRule))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_SetRuleEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.SetRuleEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).SetRuleEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_SetRuleEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).SetRuleEnabled(ctx, req.(*contracts.SetRuleEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_BulkSetRulesEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.BulkSetRulesEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).BulkSetRulesEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_BulkSetRulesEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).BulkSetRulesEnabled(ctx, req.(*contracts.BulkSetRulesEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).DeleteRule(ctx, req.(*contracts.DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).GetSettings(ctx, req.(*contracts.GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.GuardrailsSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).UpdateSettings(ctx, req.(*common.GuardrailsSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_GetDataTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.GetDataTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).GetDataTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_GetDataTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).GetDataTypes(ctx, req.(*contracts.GetDataTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).Scan(ctx, req.(*contracts.ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_ListAuditRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.ListAuditRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).ListAuditRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_ListAuditRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).ListAuditRecords(ctx, req.(*contracts.ListAuditRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_GetAuditRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.GetAuditRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).GetAuditRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_GetAuditRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).GetAuditRecord(ctx, req.(*contracts.GetAuditRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuardrailsApi_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardrailsApiServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardrailsApi_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardrailsApiServer).GetVersion(ctx, req.(*contracts.GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuardrailsApi_ServiceDesc is the grpc.ServiceDesc for GuardrailsApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuardrailsApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudru.guardrails.v1.service.GuardrailsApi",
	HandlerType: (*GuardrailsApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _GuardrailsApi_ListRules_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _GuardrailsApi_CreateRule_Handler,
		},
		{
			MethodName: "GetRule",
			Handler:    _GuardrailsApi_GetRule_Handler,
		},
		{
			MethodName: "UpdateRule",
			Handler:    _GuardrailsApi_UpdateRule_Handler,
		},
		{
			MethodName: "SetRuleEnabled",
			Handler:    _GuardrailsApi_SetRuleEnabled_Handler,
		},
		{
			MethodName: "BulkSetRulesEnabled",
			Handler:    _GuardrailsApi_BulkSetRulesEnabled_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _GuardrailsApi_DeleteRule_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _GuardrailsApi_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _GuardrailsApi_UpdateSettings_Handler,
		},
		{
			MethodName: "GetDataTypes",
			Handler:    _GuardrailsApi_GetDataTypes_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _GuardrailsApi_Scan_Handler,
		},
		{
			MethodName: "ListAuditRecords",
			Handler:    _GuardrailsApi_ListAuditRecords_Handler,
		},
		{
			MethodName: "GetAuditRecord",
			Handler:    _GuardrailsApi_GetAuditRecord_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _GuardrailsApi_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/cloudru/guardrails/v1/service/service.proto",
}
