// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/cloudru/guardrails/v1/service/swagger.proto

package servicev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_cloudru_guardrails_v1_service_swagger_proto protoreflect.FileDescriptor

const file_api_proto_cloudru_guardrails_v1_service_swagger_proto_rawDesc = "" +
	"\n" +
	"5api/proto/cloudru/guardrails/v1/service/swagger.proto\x12\x1dcloudru.guardrails.v1.service\x1a.protoc-gen-openapiv2/options/annotations.protoB\xd1\x05\x92A\xdf\x04\x12\x83\x02\n" +
	"\x19Guardrails Management API\x12\xde\x01Management API for the standalone guardrails service: custom rule CRUD, global settings, data-type discovery and dry-run masking checks. The data-plane LLM proxy is a separate HTTP surface and is not part of this contract.2\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonRV\n" +
	"\x03400\x12O\n" +
	"5Bad Request - invalid parameters or malformed request\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusR*\n" +
	"\x03404\x12#\n" +
	"\tNot Found\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusR)\n" +
	"\x03409\x12\"\n" +
	"\bConflict\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusR6\n" +
	"\x03500\x12/\n" +
	"\x15Internal Server Error\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusjH\n" +
	"\n" +
	"Guardrails\x12:Rule, settings and data-type management, plus dry-run scanZlgithub.com/cloud-ru-tech/guardrails-llm-filter-extproc/pkg/api/proto/cloudru/guardrails/v1/service;servicev1b\x06proto3"

var file_api_proto_cloudru_guardrails_v1_service_swagger_proto_goTypes = []any{}
var file_api_proto_cloudru_guardrails_v1_service_swagger_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cloudru_guardrails_v1_service_swagger_proto_init() }
func file_api_proto_cloudru_guardrails_v1_service_swagger_proto_init() {
	if File_api_proto_cloudru_guardrails_v1_service_swagger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cloudru_guardrails_v1_service_swagger_proto_rawDesc), len(file_api_proto_cloudru_guardrails_v1_service_swagger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_cloudru_guardrails_v1_service_swagger_proto_goTypes,
		DependencyIndexes: file_api_proto_cloudru_guardrails_v1_service_swagger_proto_depIdxs,
	}.Build()
	File_api_proto_cloudru_guardrails_v1_service_swagger_proto = out.File
	file_api_proto_cloudru_guardrails_v1_service_swagger_proto_goTypes = nil
	file_api_proto_cloudru_guardrails_v1_service_swagger_proto_depIdxs = nil
}
